### ISSUE TITLE
Site Is Broken In Firefox

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/bayhacks.dev#1]
Based on my testing, the site seems to work perfectly on Chrome and Safari/mobile Safari. However, it's broken in Firefox with the following error:

<img width="1510" alt="image" src="https://github.com/TampaDevs/bayhacks.dev/assets/7227500/8c56684d-17c4-462d-8254-c0d9487ef337">

**Comment by CodaBool** [comment]
Interesting, I get the same issue when trying to connect with Firefox. 
The build runs fine locally with Firefox. So, this may take some debugging.

**Comment by CodaBool** [comment]
did a redeploy and it seems to work 🤷

Can I get a test that it is working for you too @chtzvt ?

**Comment by chtzvt** [comment]
Can confirm it's working in Firefox on Windows. Thanks a ton!
