### ISSUE TITLE
Improve Asset Cacheability

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/bayhacks.dev#2]
I'd like to optimize our Cloudflare caching configuration for the site's assets to improve load times. In order to implement this, it would be helpful if assets had a normalized URL scheme to place them under a particular directory. 

Currently, these are served from the root (i.e., `https://bayhacks.dev/waves.mp3`). A scheme like `https://bayhacks.dev/assets/waves.mp3` would be awesome, so I can target `https://bayhacks.dev/assets/*` in my cache matching pattern.

**Comment by CodaBool** [comment]
> done
![assets](https://github.com/TampaDevs/bayhacks.dev/assets/61724833/315811d8-20bb-4b81-bffc-beb453e5abf4)
