### ISSUE TITLE
Google Analytics / Tag Manager

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/bayhacks.dev#4]
We use Google Analytics and Tag Manager to measure traffic and interaction with Tampa Devs web properties, along with the effectiveness of our ad campaigns (we'll be running a big one to promote Bayhacks).

Could you install the following tag on the site?

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VV1YTRRM50"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VV1YTRRM50');
</script>
```

**Comment by CodaBool** [comment]
added in [latest commit](https://github.com/TampaDevs/bayhacks.dev/blob/a563aec2917cd1649440141de76cc43d8a466903/index.html#L16). Should be deployed any minute for testing.
