### ISSUE TITLE
Regression in Firefox

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/bayhacks.dev#5]
Looks like builds are again broken in Firefox. However, I can confirm that the site runs without issue in desktop Safari.

<img width="1512" alt="image" src="https://github.com/TampaDevs/bayhacks.dev/assets/7227500/feb11de0-bdd2-45eb-9387-88d557e058cd">

**Comment by CodaBool** [comment]
This is weird I've had this happen on a build I did adding that Google analytics thing. And then I built it again with the script tag in a different spot in the head. So, there's something unstable with the build on Firefox I'm not sure what it is.

**Comment by CodaBool** [comment]
I've gone to the site a couple times in Firefox since this has been opened. Seems to be working fine for me. I think I did see that error once when you added this issue but I haven't been able to see it again

**Comment by chtzvt** [comment]
OK, could have been some kind of issue with old assets being cashed. Will continue to monitor.
