### ISSUE TITLE
Email Signup Form

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/bayhacks.dev#9]
Yo!

I made an email signup form for folks if they want to join our mailing list from the site. Anywhere you could embed it? 

```
<iframe src="https://cdn.forms-content.sg-form.com/00ccf8ee-0d7c-11ee-bf2c-16fb11e76640"/>
```

**Comment by CodaBool** [comment]
I'll look into adding this today. Thank you

**Comment by CodaBool** [comment]
tested locally with a [PR ](https://github.com/TampaDevs/bayhacks.dev/pull/10)

![Screenshot 2023-06-21 192200](https://github.com/TampaDevs/bayhacks.dev/assets/61724833/0062d6e7-4315-4846-b1c9-4af51d8d9ffd)
![Screenshot 2023-06-21 192234](https://github.com/TampaDevs/bayhacks.dev/assets/61724833/c588feae-dc52-434f-bac3-5ccf5a52eab3)

**Comment by chtzvt** [comment]
Looks awesome-- thank you!!
